version: "3.4"

services:
    postgres:
        image: postgres:13-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=midpoint
            - POSTGRES_DB=midpoint
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        networks:
            - main_network
    midpoint:
        image: evolveum/midpoint:4.4-alpine
        container_name: midpoint
        environment:
            - MP_ENTRY_POINT=/opt/midpoint-dirs-docker-entrypoint
            - REPO_DATABASE_TYPE=postgresql
            - REPO_DATABASE=midpoint
            - REPO_USER=midpoint
            - REPO_HOST=postgres
        ports:
            - 8080:8080
        networks:
            - main_network
        volumes:
            - ./midpoint/pio:/opt/midpoint-dirs-docker-entrypoint/:ro
    scim:
        image: scim-personify 
        container_name: scim
        ports: 
            - 8081:8080 # server ports
            - 9990:9990 # debug ports
        networks:
            - main_network
        volumes:
            - ./scim/schemas:/schemas
networks:
    main_network:
        driver: bridge
